version: "3"
services:

  chatbot_frontend:
    container_name: chatbot_frontend
    image: node:15.10.0-alpine3.10
    user: root
    ports:
      - "3000:8080"
    volumes:
      - ./chatbot_frontend:/home/node/app
    command: sh -c "cd /home/node/app && yarn install && yarn run start-dev"
    environment:
      CHATBOT_API_URL: <api-url>
      FORCE_RESPONSE_RATING: 'false'
      PORT: 8080
